
GET http://localhost:3000/weatherstation/updateweatherstation.php?ID=XXXXX&PASSWORD=YYYYYYY&action=updateraww&realtime=1&rtfreq=5&dateutc=now&baromin=29.91&tempf=45.3&dewptf=39.2&humidity=79&windspeedmph=0.0&windgustmph=0.0&winddir=138&rainin=0.0&dailyrainin=0.0&solarradiation=0.0&UV=0.0&indoortempf=73.9&indoorhumidity=40